version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 20s
      retries: 5

  back_service:
    build:
      context: .
      dockerfile: DockerfileBackService
    env_file:
      - .env.dev
    volumes:
      - ./endpoints:/app/endpoints
      - ./schemas:/app/schemas
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - db

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    env_file:
#      - .env.dev
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres_data:
