version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=boo
      - POSTGRES_PASSWORD=boo_pass
      - POSTGRES_DB=CellFrameDB
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres
    environment:
      - POSTGRES_USER=boo
      - POSTGRES_PASSWORD=boo_pass
      - POSTGRES_DB=CellFrameTestDB
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  back_service:
    build:
      context: .
      dockerfile: DockerfileBackService
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=boo
      - POSTGRES_PASSWORD=boo_pass
      - POSTGRES_DB=CellFrameDB
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    env_file:
#      - .env.dev
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres_data1:
  postgres_data2:
